export { MainWrapper } from './MainWrapper';
export { ErrorBoundary } from './ErrorBoundary';
export { FindCourse } from './Sections/FindCourse/FindCourse';
export { Advantages } from './Sections/Advantages/Advantages';
export { Partners } from './Sections/Partners';
export { NonStudents } from './Sections/NonStudents';
export { Courses } from './Sections/Courses';
export { ButtonCoursesType } from './ButtonCoursesType';
export { CarouselCourses } from './CarouselCourses';
export { Carousel } from './Carousel';
export { Recommendations } from './Sections/Recommendations';
export { TopCategories } from './Sections/TopCategories';
export { ItemCategory } from './Sections/TopCategories/ItemCategory';
export { Comments } from './Sections/Comments';
export { Footer } from './Footer';
export { Icon } from './Icon';

export { TextField } from './FormFields';
export { SimpleSelect } from './Fields';
